# -*- coding: utf-8 -*-
"""
Created on Sat May  2 23:27:41 2020

@author: Lingala Rohit
"""

# import folium package 
import folium 
#from IPython.display import display
# Map method of folium return Map object 

# Here we pass coordinates of Gfg 
# and starting Zoom level = 12 
hyd=(17.387140,78.491684)
rr=(17.390654, 77.834694)#ranga reddy
sr=(17.611629, 78.081810)#sanga reddy
adi=(19.666700, 78.533302)
nirmal=(19.096413, 78.342972)
kb=(19.3619,79.2930)
kg=(17.554356, 80.619736)
jagtial=(18.794905, 78.912872)
jangoan=(17.721872, 79.172287)
sp=(17.143908, 79.623924)
jb=(18.4293,79.8635)
gadwal=(16.2300,77.8000)
kr=(18.3205,78.3370)
kn=(18.438555, 79.128838)
kh=(17.247253, 80.151443)
mb=(17.6026,80.0036)
mbn=( 16.737509, 78.008125)
mh=(18.8714,79.4443)
medak=(18.045992, 78.263359)
medchal=(17.630222, 78.484215)
mulugu=(18.1932,79.9414)
nk=(16.4939,78.3102)
nd=(17.056620, 79.268333)
np=(16.745668, 77.495415)
nz=(18.6725,78.0941)
pp=(18.6151,79.3827)
rs=(18.386620, 78.802246)
sd=(18.101904, 78.852074)
vk=(17.336430, 77.904846)
wp=(16.3623,78.0622)
w=(17.956121,79.614708)
y=(17.518345, 78.885956)

my_map1 = folium.Map(location = [17.123184, 79.208824],zoom_start = 9 ) 
#folium.Marker([17.387140,78.491684], 
#               popup = 'Hyderabad').add_to(my_map1)
my_map1.circle_marker(hyd,popup = 'Hyderabad') 
my_map1.circle_marker(rr,popup = 'Ranga Reddy') 
my_map1.circle_marker(sr,popup = 'Sanga Reddy')
my_map1.circle_marker(adi,popup = 'adilabad')
my_map1.circle_marker(nirmal,popup = 'Nirmal')
my_map1.circle_marker(kb,popup = 'Kumuram Bheem')
my_map1.circle_marker(kg,popup = 'Bhadradri Kothagudam')
my_map1.circle_marker(jagtial,popup = 'Jagtial')
my_map1.circle_marker(jangoan,popup = 'Jangoan')
my_map1.circle_marker(sp,popup = 'Suryapet')
my_map1.circle_marker(jb,popup = 'Jayshankar Bupalpally')
my_map1.circle_marker(gadwal,popup = 'Gadwal')
my_map1.circle_marker(kr,popup = 'Kamareddy')
my_map1.circle_marker(kn,popup = 'Karimnagar')
my_map1.circle_marker(kh,popup = 'Khammam')
my_map1.circle_marker(mb,popup = 'Mahububabad')
my_map1.circle_marker(mbn,popup = 'Mahububnagar')
my_map1.circle_marker(mh,popup = 'Mancherial')
my_map1.circle_marker(medak,popup = 'Medak')
my_map1.circle_marker(medchal,popup = 'Medchal')
my_map1.circle_marker(mulugu,popup = 'Mulugu')
my_map1.circle_marker(nk,popup = 'NagarKurnool')
my_map1.circle_marker(nd,popup = 'Nalgonda')
my_map1.circle_marker(np,popup = 'Narayanpet')
my_map1.circle_marker(nz,popup = 'Nizamabad')
my_map1.circle_marker(pp,popup = 'Peddapalli')
my_map1.circle_marker(rs,popup = 'sirsilla')
my_map1.circle_marker(sd,popup = 'Siddipet')
my_map1.circle_marker(vk,popup = 'Vikarabad')
my_map1.circle_marker(wp,popup = 'Wanarparthy')
my_map1.circle_marker(w,popup = 'Warangal')
my_map1.circle_marker(y,popup = 'Yadadri')
#hyd to rangareddy
my_map1.line(locations = [y,nd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [y,sp],line_opacity = 5,line_weight=1)
my_map1.line(locations = [y,jangoan],line_opacity = 5,line_weight=1)
my_map1.line(locations = [w,jangoan],line_opacity = 5,line_weight=1)
my_map1.line(locations = [sp,jangoan],line_opacity = 5,line_weight=1)
my_map1.line(locations = [mb,jangoan],line_opacity = 5,line_weight=1)
my_map1.line(locations = [w,mulugu],line_opacity = 5,line_weight=1)
my_map1.line(locations = [w,mb],line_opacity = 5,line_weight=1)
my_map1.line(locations = [np,mbn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [wp,mbn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nk,mbn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [gadwal,wp],line_opacity = 5,line_weight=1)
my_map1.line(locations = [wp,nk],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nk,nd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [np,mbn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nk,nd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nd,sp],line_opacity = 5,line_weight=1)
my_map1.line(locations = [sp,mbn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [sp,kh],line_opacity = 5,line_weight=1)
my_map1.line(locations = [mbn,mulugu],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kg,mbn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kh,mbn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kh,kg],line_opacity = 5,line_weight=1)
my_map1.line(locations = [np,gadwal],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kg,mb],line_opacity = 5,line_weight=1)
my_map1.line(locations = [medchal,rr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [medchal,y],line_opacity = 5,line_weight=1)
my_map1.line(locations = [hyd,medchal],line_opacity = 5,line_weight=1)
my_map1.line(locations = [np,rr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [mbn,rr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nk,rr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nd,rr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [y,rr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [vk,rr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [vk,mbn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [vk,np],line_opacity = 5,line_weight=1)
my_map1.line(locations = [medchal,sd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [y,sd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [jangoan,sd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [w,sd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [medak,sd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [medak,medchal],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kn,sd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kn,w],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kn,jb],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kn,pp],line_opacity = 5,line_weight=1)
my_map1.line(locations = [hyd,rr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [jb,mulugu],line_opacity = 5,line_weight=1)
my_map1.line(locations = [jb,w],line_opacity = 5,line_weight=1)
my_map1.line(locations = [jb,pp],line_opacity = 5,line_weight=1)
my_map1.line(locations = [rr,sr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [vk,sr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [medchal,sr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [medak,sr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [adi,nirmal],line_opacity = 5,line_weight=1)
my_map1.line(locations = [adi,kb],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nirmal,nz],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nirmal,jagtial],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nz,kr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nz,rs],line_opacity = 5,line_weight=1)
my_map1.line(locations = [nz,jagtial],line_opacity = 5,line_weight=1)
my_map1.line(locations = [jagtial,mh],line_opacity = 5,line_weight=1)
my_map1.line(locations = [jagtial,kn],line_opacity = 5,line_weight=1)
my_map1.line(locations = [jagtial,pp],line_opacity = 5,line_weight=1)
my_map1.line(locations = [mh,kb],line_opacity = 5,line_weight=1)
my_map1.line(locations = [mh,pp],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kr,medak],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kr,rs],line_opacity = 5,line_weight=1)
my_map1.line(locations = [kr,sr],line_opacity = 5,line_weight=1)
my_map1.line(locations = [rs,sd],line_opacity = 5,line_weight=1)
my_map1.line(locations = [rs,kn],line_opacity = 5,line_weight=1)

# save method of Map object will create a map 
my_map1.create_map(path='my_map1.html')
#my_map1.save('my_map1.html') 
display(my_map1)
my_map1.display()

